//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string Bio { get; set; }
        public string FavouriteExercise { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<bool> Private { get; set; }
    
        public virtual User User { get; set; }
    }
}
