//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WorkoutId { get; set; }
        public Nullable<int> InResponseToComment { get; set; }
        public int Upvotes { get; set; }
        public int Downvotes { get; set; }
        public Nullable<bool> Spam { get; set; }
    
        public virtual User User { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
