//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineProfile
    {
        public int OnlineProfileId { get; set; }
        public int UserId { get; set; }
        public string Bio { get; set; }
        public Nullable<int> Age { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
    }
}
