//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineSet
    {
        public int OnlineSetId { get; set; }
        public string ExerciseName { get; set; }
        public string Handle { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Reps { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
