//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineWorkout
    {
        public int OnlineWorkoutId { get; set; }
        public int UserId { get; set; }
        public string WorkoutString { get; set; }
        public Nullable<System.DateTime> DateOfSubmission { get; set; }
        public Nullable<System.DateTime> WorkoutDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
